### ISSUE TITLE
The demo doesn't run good in Delphi 10.1, error

### ISSUE THREAD

**Issue by blaisexen** [DelphiWorlds/Camera#7]
Isn't responding

**Comment by blaisexen** [comment]
I also installed 10.2, but keeps hanging, only shows the Delphi android symbol

**Comment by DelphiWorlds** [comment]
It was working for me in Delphi 10.1 Berlin, and I'm pretty sure Delphi 10.2 Tokyo. I'll check again soon

**Comment by DelphiWorlds** [comment]
What version of Android are you running? Note that this project requires Android 5 or higher.

**Comment by blaisexen** [comment]
hi,

that's why isn't responding because I used 4.+ kitkat,

thanks for the info.
