### ISSUE TITLE
compile for Win32 ?

### ISSUE THREAD

**Issue by wesleybobato** [DelphiWorlds/Camera#8]
Hello Dave Nottage

Good afternoon :)

Is it possible to compile for Win32?

is it possible to use face detection with Windows?

Thank you for your attention, have a wonderful day.

Please change

unit DW.Camera;

uses
   // FMX
   FMX.Types,
   // DW
{$ IFDEF ANDROID}
   DW.Camera.Android;
{$ ENDIF}

**uses
   // FMX
   FMX.Types
   // DW
{$ IFDEF ANDROID}
   , DW.Camera.Android
{$ ENDIF}
   ;**

**Comment by wesleybobato** [comment]
Sorry, I forgot to tell you.

I'm using Delphi Tokyo 10.2.2

**Comment by DelphiWorlds** [comment]
Sorry, no Windows support in this project - that involves a fair amount of work that I don't have time for. I might had the iOS support I've done, though

**Comment by wesleybobato** [comment]
no problem
Thank you very much for your wonderful attention.

have an excellent day :)
